package site.addzero.lsi.jimmer.client

import site.addzero.lsi.clazz.LsiClass
import site.addzero.lsi.clazz.annotation
import site.addzero.lsi.clazz.packageAnnotation
import site.addzero.lsi.jimmer.EXPORT_DOC
import site.addzero.lsi.resolver.LsiResolver
import java.io.Writer
import java.util.Properties
import java.util.regex.Pattern

object LsiExportDocSupport {

    @JvmStatic
    fun collectExportDocTypeNames(
        resolver: LsiResolver
    ): Set<String> {
        val pkg = exportDocPkg(resolver)
        val declarations = linkedMapOf<String, LsiClass>()
        for (lsiClass in resolver.allClasses()) {
            val packageName = lsiClass.packageName
            collectExportDocDeclaration(pkg.isExported(packageName), lsiClass, declarations)
        }
        return declarations.keys
    }

    @JvmStatic
    fun resolveExportDocDeclarations(
        resolver: LsiResolver,
        typeNames: Collection<String>
    ): List<LsiClass> =
        typeNames
            .mapNotNull { resolver.findClassByQualifiedName(it) }
            .toList()

    @JvmStatic
    fun writeExportDoc(
        declarations: List<LsiClass>,
        writer: Writer
    ) {
        val properties = Properties()
        for (declaration in declarations) {
            addExportDocProperties(properties, declaration)
        }
        // 覆盖来源：project/compiler/client/jimmer-ksp-client/.../ExportDocProcessor.writeDoc 输出备注
        // 覆盖来源：project/jimmer-apt/.../client/ExportDocProcessor.writeDoc 输出备注
        // 迁移说明：导出注释写出逻辑下沉到共享 Jimmer-LSI helper，APT/KSP 入口都只保留 orchestration 与资源落盘职责
        properties.store(writer, "Generated by @$EXPORT_DOC")
    }

    private fun collectExportDocDeclaration(
        parentExport: Boolean,
        declaration: LsiClass,
        declarations: MutableMap<String, LsiClass>
    ) {
        val isClassLike = !declaration.isInterface || declaration.isEnum
        if (!isClassLike) {
            return
        }
        // 覆盖来源：project/compiler/client/jimmer-ksp-client/.../ExportDocProcessor.collectDeclaration @ExportDoc 读取
        // 覆盖来源：project/jimmer-apt/.../client/ExportDocProcessor.collectTypeElements @ExportDoc 读取
        // 迁移说明：ExportDoc 导出判定与递归收集规则下沉为共享 LSI helper，后续 APT/KSP 共用同一语义函数
        val exportDoc = declaration.annotation(EXPORT_DOC)
        val export = if (exportDoc != null) {
            !(exportDoc.getAttribute("excluded") as? Boolean ?: false)
        } else {
            parentExport
        }
        if (export) {
            declaration.qualifiedName?.let { declarations[it] = declaration }
        }
        for (field in declaration.fields.filter { it.isNestedObject }) {
            field.fieldTypeClass?.let { nestedClass ->
                collectExportDocDeclaration(export, nestedClass, declarations)
            }
        }
    }

    private fun exportDocPkg(resolver: LsiResolver): ExportDocPkg {
        val pkg = ExportDocPkg("", null)
        // 覆盖来源：project/compiler/client/jimmer-ksp-client/.../ExportDocProcessor.pkg
        // 覆盖来源：project/jimmer-apt/.../client/ExportDocProcessor.pkg
        // 迁移说明：包级 `@ExportDoc` 读取统一经由 `LsiClass.packageAnnotations` 收敛，
        // 业务层不再区分 `PackageElement` 与 Kotlin `@file:` 注解载体
        for (lsiClass in resolver.allClasses()) {
            val packageName = lsiClass.packageName ?: continue
            val exportDoc = lsiClass.packageAnnotation(EXPORT_DOC) ?: continue
            pkg.setExported(
                packageName = packageName,
                export = !(exportDoc.getAttribute("excluded") as? Boolean ?: false)
            )
        }
        return pkg
    }

    private fun addExportDocProperties(
        properties: Properties,
        declaration: LsiClass
    ) {
        val qualifiedName = declaration.qualifiedName ?: return
        standardExportDocComment(declaration.comment)?.let {
            properties[qualifiedName] = it
        }
        for (prop in declaration.fields.filter { !it.isStatic && !it.isConstant }) {
            val propName = "$qualifiedName.${prop.name}"
            standardExportDocComment(prop.comment)?.let {
                properties[propName] = it
            }
        }
    }

    private fun standardExportDocComment(comment: String?): String? =
        comment
            ?.trim()
            ?.takeIf { it.isNotEmpty() }

    private class ExportDocPkg(
        val name: String,
        private val parent: ExportDocPkg?
    ) {
        private var childMap: MutableMap<String, ExportDocPkg>? = null

        var export: Boolean? = null

        fun setExported(packageName: String, export: Boolean) {
            sub(packageName, autoCreate = true).export = export
        }

        fun isExported(packageName: String?): Boolean {
            packageName ?: return false
            var pkg = sub(packageName, autoCreate = false)
            while (true) {
                if (pkg.export != null) {
                    return pkg.export!!
                }
                pkg = pkg.parent ?: break
            }
            return false
        }

        fun sub(packageName: String, autoCreate: Boolean): ExportDocPkg {
            var pkg = this
            for (name in DOT_PATTERN.split(packageName)) {
                val childPkg = pkg.child(name, autoCreate)
                if (childPkg == null) {
                    return pkg
                }
                pkg = childPkg
            }
            return pkg
        }

        private fun child(name: String, autoCreate: Boolean): ExportDocPkg? {
            if (!autoCreate && childMap == null) {
                return null
            }
            val childMap = this.childMap ?: mutableMapOf<String, ExportDocPkg>().also {
                this.childMap = it
            }
            if (!autoCreate) {
                return childMap[name]
            }
            return childMap.computeIfAbsent(name) {
                ExportDocPkg(name, this)
            }
        }

        companion object {
            private val DOT_PATTERN = Pattern.compile("\\.")
        }
    }
}
