package site.addzero.lsi.jimmer.client.metadata.generator

import site.addzero.lsi.clazz.LsiClass
import site.addzero.lsi.codegen.GeneratedResourceArtifact
import site.addzero.lsi.jimmer.client.LsiExportDocSupport
import java.io.StringWriter

class ExportDocResourceGenerator {

    fun generate(
        declarations: List<LsiClass>,
    ): GeneratedResourceArtifact {
        val writer = StringWriter()
        LsiExportDocSupport.writeExportDoc(declarations, writer)
        return GeneratedResourceArtifact(
            path = RESOURCE_PATH,
            content = writer.toString(),
        )
    }

    companion object {
        const val RESOURCE_PATH = "META-INF/jimmer/doc.properties"
        const val RESOURCE_COMMENT = "Generated by @org.babyfish.jimmer.client.ExportDoc"
    }
}
