package org.babyfish.jimmer.compiler.exportdoc

import site.addzero.lsi.codegen.ArtifactAggregationMode
import site.addzero.lsi.codegen.ArtifactKind
import site.addzero.lsi.codegen.GeneratedArtifact
import site.addzero.lsi.jimmer.exportdoc.ExportDocEntry
import site.addzero.lsi.jimmer.exportdoc.ExportDocSchema
import site.addzero.lsi.model.LsiWorkspace

class ExportDocResourceRenderer {

    fun render(
        schema: ExportDocSchema,
        workspace: LsiWorkspace,
    ): GeneratedArtifact? {
        if (schema.exportedTypeIds.isEmpty()) {
            return null
        }
        val originatingSymbols = buildSet {
            addAll(schema.effectiveConfigurationIds)
            addAll(schema.exportedTypeIds)
            schema.entries.mapTo(this, ExportDocEntry::declarationId)
        }
        return GeneratedArtifact.create(
            kind = ArtifactKind.RESOURCE,
            path = EXPORT_DOC_RESOURCE_PATH,
            content = schema.propertiesContent(),
            aggregationMode = ArtifactAggregationMode.AGGREGATING,
            originatingSymbols = originatingSymbols,
            originatingSources = workspace.originatingSources(originatingSymbols),
        )
    }
}

private fun ExportDocSchema.propertiesContent(): String {
    return buildString {
        append(EXPORT_DOC_HEADER)
        append('\n')
        entries.forEach { entry ->
            append(entry.key.escapeProperty(convertSpace = true))
            append('=')
            append(entry.content.escapeProperty(convertSpace = false))
            append('\n')
        }
    }
}

private fun String.escapeProperty(convertSpace: Boolean): String {
    return buildString(length) {
        for ((index, character) in this@escapeProperty.withIndex()) {
            when (character) {
                ' ' -> {
                    if (index == 0 || convertSpace) {
                        append('\\')
                    }
                    append(' ')
                }
                '\\' -> append("\\\\")
                '\t' -> append("\\t")
                '\n' -> append("\\n")
                '\r' -> append("\\r")
                '\u000c' -> append("\\f")
                '=', ':', '#', '!' -> {
                    append('\\')
                    append(character)
                }
                else -> append(character)
            }
        }
    }
}

const val EXPORT_DOC_RESOURCE_PATH = "META-INF/jimmer/doc.properties"

private const val EXPORT_DOC_HEADER =
    "#Generated by @org.babyfish.jimmer.client.ExportDoc"
