package org.babyfish.jimmer.ddl.generator.dialect.oracle

import org.babyfish.jimmer.ddl.generator.dialect.AbstractSqlDialect
import org.babyfish.jimmer.ddl.generator.diff.CreateSequence
import org.babyfish.jimmer.ddl.generator.model.AutoDdlColumn
import org.babyfish.jimmer.ddl.generator.model.AutoDdlLogicalType
import org.babyfish.jimmer.ddl.compiler.JimmerDatabaseType

class OracleAutoDdlDialect : AbstractSqlDialect(JimmerDatabaseType.ORACLE) {

    override fun renderCreateSequence(operation: CreateSequence): String {
        return "CREATE SEQUENCE ${quoteIdentifier(operation.sequence.name)} START WITH ${operation.sequence.startWith} INCREMENT BY ${operation.sequence.incrementBy}"
    }

    override fun renderDropTable(tableName: String): String {
        return "DROP TABLE ${quoteIdentifier(tableName)}"
    }

    override fun renderAutoIncrementClause(column: AutoDdlColumn): String? {
        return if (column.autoIncrement) "GENERATED BY DEFAULT AS IDENTITY" else null
    }

    override fun columnType(column: AutoDdlColumn): String {
        return when (column.logicalType) {
            AutoDdlLogicalType.STRING -> "VARCHAR2(${column.length ?: 255})"
            AutoDdlLogicalType.TEXT -> "CLOB"
            AutoDdlLogicalType.CHAR -> "CHAR(${column.length ?: 1})"
            AutoDdlLogicalType.BOOLEAN -> "NUMBER(1)"
            AutoDdlLogicalType.INT8,
            AutoDdlLogicalType.INT16,
            AutoDdlLogicalType.INT32 -> "NUMBER(10)"
            AutoDdlLogicalType.INT64 -> "NUMBER(19)"
            AutoDdlLogicalType.DECIMAL -> "NUMBER(${column.precision ?: 19}, ${column.scale ?: 2})"
            AutoDdlLogicalType.BIG_INTEGER -> "NUMBER(38)"
            AutoDdlLogicalType.FLOAT32,
            AutoDdlLogicalType.FLOAT64 -> "BINARY_DOUBLE"
            AutoDdlLogicalType.DATE -> "DATE"
            AutoDdlLogicalType.TIME -> "TIMESTAMP"
            AutoDdlLogicalType.DATETIME,
            AutoDdlLogicalType.TIMESTAMP,
            AutoDdlLogicalType.DATETIME_TZ -> "TIMESTAMP"
            AutoDdlLogicalType.DURATION -> "NUMBER(19)"
            AutoDdlLogicalType.BINARY -> "BLOB"
            AutoDdlLogicalType.UUID -> "VARCHAR2(36)"
            AutoDdlLogicalType.JSON -> "CLOB"
            AutoDdlLogicalType.UNKNOWN -> column.nativeTypeHint ?: "VARCHAR2(255)"
        }
    }
}
