package org.babyfish.jimmer.compiler.exportdoc

import java.io.StringReader
import java.util.Properties
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNull
import site.addzero.lsi.codegen.ArtifactAggregationMode
import site.addzero.lsi.codegen.ArtifactKind
import site.addzero.lsi.core.LsiLanguage
import site.addzero.lsi.core.LsiOrigin
import site.addzero.lsi.core.LsiOriginKind
import site.addzero.lsi.core.LsiSource
import site.addzero.lsi.core.LsiSymbolId
import site.addzero.lsi.jimmer.exportdoc.ExportDocEntry
import site.addzero.lsi.jimmer.exportdoc.ExportDocSchema
import site.addzero.lsi.model.LsiAnnotation
import site.addzero.lsi.type.LsiDeclaredType
import site.addzero.lsi.model.LsiPackageAnnotationScope
import site.addzero.lsi.model.LsiProperty
import site.addzero.lsi.model.LsiTypeDeclaration
import site.addzero.lsi.model.LsiTypeDeclarationKind
import site.addzero.lsi.model.LsiWorkspace

class ExportDocResourceRendererTest {

    @Test
    fun `renders deterministic standard properties content and round trips`() {
        val scope = packageScope()
        val type = type("demo.Special")
        val property = property(type.id, "value")
        val schema = ExportDocSchema(
            effectiveConfigurationIds = listOf(scope.id),
            exportedTypeIds = listOf(type.id),
            entries = listOf(
                ExportDocEntry(
                    declarationId = property.id,
                    key = "demo.Special key",
                    content = " leading\nline\t=:#!",
                )
            ),
        )
        val workspace = LsiWorkspace(
            declarations = listOf(type, property),
            annotationScopes = listOf(scope),
        )

        val artifact = requireNotNull(ExportDocResourceRenderer().render(schema, workspace))

        assertEquals(ArtifactKind.RESOURCE, artifact.kind)
        assertEquals(EXPORT_DOC_RESOURCE_PATH, artifact.path)
        assertEquals(ArtifactAggregationMode.AGGREGATING, artifact.aggregationMode)
        assertEquals(
            """
                #Generated by @org.babyfish.jimmer.client.ExportDoc
                demo.Special\ key=\ leading\nline\t\=\:\#\!
            """.trimIndent() + "\n",
            artifact.content,
        )
        val properties = Properties().also { properties ->
            properties.load(StringReader(artifact.content))
        }
        assertEquals(" leading\nline\t=:#!", properties.getProperty("demo.Special key"))
        assertEquals(setOf(scope.id, type.id, property.id), artifact.originatingSymbols)
        assertEquals(
            setOf(scope.origin.source, type.origin.source, property.origin.source),
            artifact.originatingSources,
        )
    }

    @Test
    fun `exports header only when configured types have no docs`() {
        val type = type("demo.Empty")
        val schema = ExportDocSchema(
            effectiveConfigurationIds = listOf(type.id),
            exportedTypeIds = listOf(type.id),
            entries = emptyList(),
        )

        val artifact = requireNotNull(
            ExportDocResourceRenderer().render(
                schema,
                LsiWorkspace(declarations = listOf(type)),
            )
        )

        assertEquals(
            "#Generated by @org.babyfish.jimmer.client.ExportDoc\n",
            artifact.content,
        )
    }

    @Test
    fun `does not render when no types are exported`() {
        val schema = ExportDocSchema(
            effectiveConfigurationIds = listOf(LsiSymbolId.packageScope("demo")),
            exportedTypeIds = emptyList(),
            entries = emptyList(),
        )

        assertNull(ExportDocResourceRenderer().render(schema, LsiWorkspace.EMPTY))
    }

    private fun packageScope(): LsiPackageAnnotationScope {
        return LsiPackageAnnotationScope(
            packageName = "demo",
            annotations = listOf(LsiAnnotation(EXPORT_DOC)),
            origin = origin("src/main/java/demo/package-info.java", LsiLanguage.JAVA),
        )
    }

    private fun type(qualifiedName: String): LsiTypeDeclaration {
        return LsiTypeDeclaration(
            id = LsiSymbolId.type(qualifiedName),
            name = qualifiedName.substringAfterLast('.'),
            qualifiedName = qualifiedName,
            kind = LsiTypeDeclarationKind.CLASS,
            origin = origin("src/main/kotlin/demo/${qualifiedName.substringAfterLast('.')}.kt", LsiLanguage.KOTLIN),
        )
    }

    private fun property(ownerId: LsiSymbolId, name: String): LsiProperty {
        return LsiProperty(
            id = LsiSymbolId.property(ownerId, name),
            name = name,
            ownerId = ownerId,
            type = LsiDeclaredType(STRING_TYPE),
            origin = origin("src/main/kotlin/demo/Special.kt", LsiLanguage.KOTLIN),
        )
    }

    private fun origin(path: String, language: LsiLanguage): LsiOrigin {
        return LsiOrigin(
            kind = LsiOriginKind.SOURCE,
            source = LsiSource.of(path, language),
        )
    }

    private companion object {
        val EXPORT_DOC = LsiSymbolId.type("org.babyfish.jimmer.client.ExportDoc")
        val STRING_TYPE = LsiSymbolId.type("java.lang.String")
    }
}
