package org.babyfish.jimmer.ddl.generator.dialect.kingbase

import org.babyfish.jimmer.ddl.generator.dialect.AbstractSqlDialect
import org.babyfish.jimmer.ddl.generator.diff.CreateSequence
import org.babyfish.jimmer.ddl.generator.model.AutoDdlColumn
import org.babyfish.jimmer.ddl.generator.model.AutoDdlLogicalType
import org.babyfish.jimmer.ddl.compiler.JimmerDatabaseType

class KingbaseAutoDdlDialect : AbstractSqlDialect(JimmerDatabaseType.KINGBASE) {

    override fun renderCreateSequence(operation: CreateSequence): String {
        return "CREATE SEQUENCE IF NOT EXISTS ${quoteIdentifier(operation.sequence.name)} START WITH ${operation.sequence.startWith} INCREMENT BY ${operation.sequence.incrementBy}"
    }

    override fun renderAlterColumn(tableName: String, column: AutoDdlColumn): List<String> {
        val table = quoteIdentifier(tableName)
        val columnName = quoteIdentifier(column.name)
        return buildList {
            add("ALTER TABLE $table ALTER COLUMN $columnName TYPE ${columnType(column)}")
            add(
                if (column.nullable) {
                    "ALTER TABLE $table ALTER COLUMN $columnName DROP NOT NULL"
                } else {
                    "ALTER TABLE $table ALTER COLUMN $columnName SET NOT NULL"
                }
            )
            column.defaultValue?.let {
                add("ALTER TABLE $table ALTER COLUMN $columnName SET DEFAULT $it")
            }
        }
    }

    override fun renderAutoIncrementClause(column: AutoDdlColumn): String? {
        return if (column.autoIncrement) "GENERATED BY DEFAULT AS IDENTITY" else null
    }

    override fun columnType(column: AutoDdlColumn): String {
        return when (column.logicalType) {
            AutoDdlLogicalType.STRING -> "VARCHAR(${column.length ?: 255})"
            AutoDdlLogicalType.TEXT -> "TEXT"
            AutoDdlLogicalType.CHAR -> "CHAR(${column.length ?: 1})"
            AutoDdlLogicalType.BOOLEAN -> "BOOLEAN"
            AutoDdlLogicalType.INT8 -> "SMALLINT"
            AutoDdlLogicalType.INT16 -> "SMALLINT"
            AutoDdlLogicalType.INT32 -> "INTEGER"
            AutoDdlLogicalType.INT64 -> "BIGINT"
            AutoDdlLogicalType.DECIMAL -> "NUMERIC(${column.precision ?: 19}, ${column.scale ?: 2})"
            AutoDdlLogicalType.BIG_INTEGER -> "NUMERIC(65, 0)"
            AutoDdlLogicalType.FLOAT32 -> "REAL"
            AutoDdlLogicalType.FLOAT64 -> "DOUBLE PRECISION"
            AutoDdlLogicalType.DATE -> "DATE"
            AutoDdlLogicalType.TIME -> "TIME"
            AutoDdlLogicalType.DATETIME, AutoDdlLogicalType.TIMESTAMP -> "TIMESTAMP"
            AutoDdlLogicalType.DATETIME_TZ -> "TIMESTAMP WITH TIME ZONE"
            AutoDdlLogicalType.DURATION -> "INTERVAL"
            AutoDdlLogicalType.BINARY -> "BYTEA"
            AutoDdlLogicalType.UUID -> "UUID"
            AutoDdlLogicalType.JSON -> "JSONB"
            AutoDdlLogicalType.UNKNOWN -> column.nativeTypeHint ?: "TEXT"
        }
    }
}
